PVGIS-SARAH Message

* System losses(%):	14
* AOI loss (%): 2.9
* Spectral effects (%): 0
* Temperature and low irradiance loss (%): 8
* Combined losses (%): 24.2
* Fixed system
* Ed: Average daily energy production from the given system (kWh)
* Em: Average monthly energy production from the given system (kWh)
* Hd: Average daily sum of global irradiation per square meter received by the modules of the given system (kWh/m2)
* Hm: Average monthly sum of global irradiation per square meter received by the modules of the given system (kWh/m2)
* SDm: Standard deviation of the monthly energy production due to year-to-year variation  (kWh)

PVGIS-NSRDB Message

* System losses(%):	14
* AOI loss (%): 2.7
* Spectral effects (%): 0
* Temperature and low irradiance loss (%): 8
* Combined losses (%): 24.1
* Fixed system
* Ed: Average daily energy production from the given system (kWh)
* Em: Average monthly energy production from the given system (kWh)
* Hd: Average daily sum of global irradiation per square meter received by the modules of the given system (kWh/m2)
* Hm: Average monthly sum of global irradiation per square meter received by the modules of the given system (kWh/m2)
* SDm: Standard deviation of the monthly energy production due to year-to-year variation  (kWh)

In [1]:
import pandas as pd
import requests
import time
from io import StringIO
import numpy as np
from tqdm import tqdm

In [2]:
def set_url(url_base, data_dic):
    url = url_base
    for key in data_dic.keys():
        url += str(key)+'='+str(data_dic[key]) + '&'
    url = url[:-1]
    return url

def get_dataframe_from_text(text):
    s=text
    substring_data = s[s.find('Month'):s.find('\r\n\tAOI loss')]
    substring_data = substring_data.replace('\t\t',',')
    substring_data = substring_data.replace('\r','')
    TESTDATA = StringIO(substring_data)
    df = pd.read_csv(TESTDATA, sep=",")
    return df

def set_df_pvgis_format(df_in, coluna_selecionada):
    values = df_in.loc[:,[coluna_selecionada]].values
    a = values.copy()
    a = np.delete(a, -1)
    a = np.insert(a, 0, values[-1])
    return a

In [3]:
df_direct = pd.read_csv('radiacao_PE/direct_normal_means_PE.csv', sep=';')
df_direct.head()

,ID,UF,LON,LAT,ANNUAL,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
0,35974,Pernambuco,-40.749,-9.5005,5668,6173,5241,5408,4725,5075,5211,5495,6061,6321,5986,6396,5923
1,35975,Pernambuco,-40.649,-9.5005,5582,6040,5233,5380,4647,4964,5054,5346,5877,6315,5978,6300,5851
2,35976,Pernambuco,-40.549,-9.5005,5468,6056,5171,5296,4613,4788,4835,5082,5744,6248,5879,6082,5821
3,36352,Pernambuco,-40.749,-9.4005,5683,6128,5244,5397,4791,5068,5230,5535,5954,6348,6058,6434,6004
4,36353,Pernambuco,-40.649,-9.4005,5652,6121,5262,5368,4700,4921,5065,5351,5903,6534,6134,6437,6029

In [4]:
df_pvgis_sarah_Em = df_direct.copy()
df_pvgis_sarah_Hm = df_direct.copy()
df_pvgis_sarah_SDm = df_direct.copy()

df_pvgis_nsrdb_Em = df_direct.copy()
df_pvgis_nsrdb_Hm = df_direct.copy()
df_pvgis_nsrdb_SDm = df_direct.copy()

In [6]:
parametros = {'lat': -8.412, 'lon': -37.592, 'raddatabase':'PVGIS-SARAH', 'peakpower':1, 'loss':14, 'inclined_optimum':1, 'vertical_optimum':1}
url_base = 'http://re.jrc.ec.europa.eu/pvgis5/PVcalc.php?'
url = set_url(url_base, parametros)
r = requests.post(url)
df = get_dataframe_from_text(r.text)
print(r.text)
df.head(13)

Latitude (decimal degrees):	-8.412
Longitude (decimal degrees):	-37.592
Radiation database:	PVGIS-SARAH
Nominal power of the PV system (Unknown type) (kWp):	1
System losses(%):	14
Fixed slope of modules (deg.):	0
Orientation (azimuth) of modules:	0

		Fixed angle
Month		Ed		Em		Hd		Hm		SDm
1		4.88		151		6.43		199		9.75
2		4.82		135		6.35		178		8.50
3		4.68		145		6.17		191		6.74
4		4.33		130		5.72		172		7.72
5		3.61		112		4.78		148		10.7
6		3.31		99.4		4.40		132		8.10
7		3.54		110		4.70		146		9.21
8		4.13		128		5.47		170		9.87
9		4.83		145		6.36		191		7.76
10		5.12		159		6.74		209		7.73
11		5.33		160		7.00		210		8.56
12		4.98		154		6.56		203		6.93
Year		4.46		136		5.89		179		3.98
	AOI loss (%)	 Spectral effects (%)	 Temperature and low irradiance loss (%)	 Combined losses (%)
Fixed system:	2.9	 ?(0)	8.0	24.2

Ed: Average daily energy production from the given system (kWh)
Em: Average monthly energy production from the given system (kWh)
Hd: Average daily sum of global irradiation per square meter received by the modules of the given system (kWh/m2)
Hm: Average monthly sum of global irradiation per square meter received by the modules of the given system (kWh/m2)
SDm: Standard deviation of the monthly energy production due to year-to-year variation  (kWh)


PVGIS (c) European Communities, 2001-2016

   Month    Ed     Em    Hd   Hm    SDm
0      1  4.88  151.0  6.43  199   9.75
1      2  4.82  135.0  6.35  178   8.50
2      3  4.68  145.0  6.17  191   6.74
3      4  4.33  130.0  5.72  172   7.72
4      5  3.61  112.0  4.78  148  10.70
5      6  3.31   99.4  4.40  132   8.10
6      7  3.54  110.0  4.70  146   9.21
7      8  4.13  128.0  5.47  170   9.87
8      9  4.83  145.0  6.36  191   7.76
9     10  5.12  159.0  6.74  209   7.73
10    11  5.33  160.0  7.00  210   8.56
11    12  4.98  154.0  6.56  203   6.93
12  Year  4.46  136.0  5.89  179   3.98

In [7]:
parametros = {'lat': -8.412, 'lon': -37.592, 'raddatabase':'PVGIS-NSRDB', 'peakpower':1, 'loss':14, 'inclined_optimum':1, 'vertical_optimum':1}
url_base = 'http://re.jrc.ec.europa.eu/pvgis5/PVcalc.php?'
url = set_url(url_base, parametros)
r = requests.post(url)
df = get_dataframe_from_text(r.text)
print(r.text)
df.head(13)

Latitude (decimal degrees):	-8.412
Longitude (decimal degrees):	-37.592
Radiation database:	PVGIS-NSRDB
Nominal power of the PV system (Unknown type) (kWp):	1
System losses(%):	14
Fixed slope of modules (deg.):	0
Orientation (azimuth) of modules:	0

		Fixed angle
Month		Ed		Em		Hd		Hm		SDm
1		4.99		155		6.58		204		7.19
2		4.93		138		6.49		182		8.28
3		4.88		151		6.43		199		6.87
4		4.53		136		5.97		179		7.83
5		3.81		118		5.05		156		9.50
6		3.48		104		4.61		138		5.75
7		3.78		117		5.00		155		7.44
8		4.45		138		5.88		182		5.25
9		4.99		150		6.56		197		19.7
10		5.34		166		7.01		217		5.71
11		5.47		164		7.18		215		8.82
12		5.10		158		6.72		208		8.63
Year		4.64		141		6.12		186		2.53
	AOI loss (%)	 Spectral effects (%)	 Temperature and low irradiance loss (%)	 Combined losses (%)
Fixed system:	2.7	 ?(0)	8.0	24.1

Ed: Average daily energy production from the given system (kWh)
Em: Average monthly energy production from the given system (kWh)
Hd: Average daily sum of global irradiation per square meter received by the modules of the given system (kWh/m2)
Hm: Average monthly sum of global irradiation per square meter received by the modules of the given system (kWh/m2)
SDm: Standard deviation of the monthly energy production due to year-to-year variation  (kWh)


PVGIS (c) European Communities, 2001-2016

   Month    Ed   Em    Hd   Hm    SDm
0      1  4.99  155  6.58  204   7.19
1      2  4.93  138  6.49  182   8.28
2      3  4.88  151  6.43  199   6.87
3      4  4.53  136  5.97  179   7.83
4      5  3.81  118  5.05  156   9.50
5      6  3.48  104  4.61  138   5.75
6      7  3.78  117  5.00  155   7.44
7      8  4.45  138  5.88  182   5.25
8      9  4.99  150  6.56  197  19.70
9     10  5.34  166  7.01  217   5.71
10    11  5.47  164  7.18  215   8.82
11    12  5.10  158  6.72  208   8.63
12  Year  4.64  141  6.12  186   2.53

In [5]:
for i in tqdm(range(0,len(df_pvgis_sarah_Em))):
    
    lat = df_pvgis_sarah_Em.iloc[i,3]
    lon = df_pvgis_sarah_Em.iloc[i,2]
    parametros = {'lat': lat, 'lon': lon, 'raddatabase':'PVGIS-SARAH', 'peakpower':1, 'loss':14, 'inclined_optimum':1, 'vertical_optimum':1}
    url_base = 'http://re.jrc.ec.europa.eu/pvgis5/PVcalc.php?'
    url = set_url(url_base, parametros)
    r = requests.post(url)
    df_vol = get_dataframe_from_text(r.text)
    df_pvgis_sarah_Em.iloc[i,4:] = set_df_pvgis_format(df_vol, 'Em')
    df_pvgis_sarah_Hm.iloc[i,4:] = set_df_pvgis_format(df_vol, 'Hm')
    df_pvgis_sarah_SDm.iloc[i,4:] = set_df_pvgis_format(df_vol, 'SDm')
    
    time.sleep(0.01)

    parametros = {'lat': lat, 'lon': lon, 'raddatabase':'PVGIS-NSRDB', 'peakpower':1, 'loss':14, 'inclined_optimum':1, 'vertical_optimum':1}
    url_base = 'http://re.jrc.ec.europa.eu/pvgis5/PVcalc.php?'
    url = set_url(url_base, parametros)
    r = requests.post(url)
    df_vol = get_dataframe_from_text(r.text)  
    df_pvgis_nsrdb_Em.iloc[i,4:] = set_df_pvgis_format(df_vol, 'Em')
    df_pvgis_nsrdb_Hm.iloc[i,4:] = set_df_pvgis_format(df_vol, 'Hm')
    df_pvgis_nsrdb_SDm.iloc[i,4:] = set_df_pvgis_format(df_vol, 'SDm')
    
    time.sleep(0.01)

100%|████████████████████████████████████████████████████████████████████████████████| 941/941 [39:30<00:00,  2.48s/it]

In [10]:
df_pvgis_sarah_Em.to_csv('PVGIS_PE\df_pvgis_sarah_Em.csv', index=None, sep=';')
df_pvgis_sarah_Hm.to_csv('PVGIS_PE\df_pvgis_sarah_Hm.csv', index=None, sep=';')
df_pvgis_sarah_SDm.to_csv('PVGIS_PE\df_pvgis_sarah_SDm.csv', index=None, sep=';')
df_pvgis_nsrdb_Em.to_csv('PVGIS_PE\df_pvgis_nsrdb_Em.csv', index=None, sep=';')
df_pvgis_nsrdb_Hm.to_csv('PVGIS_PE\df_pvgis_nsrdb_Hm.csv', index=None, sep=';')
df_pvgis_nsrdb_SDm.to_csv('PVGIS_PE\df_pvgis_nsrdb_SDm.csv', index=None, sep=';')